# Copy shared Play signing assets from fash-android-mobile into personal-os secrets/
# then push GitHub secrets. Reuses upload keystore (key0) + Play service account from Fash stack.
#
# Usage:
#   .\scripts\sync_android_secrets_from_fash.ps1
#   .\scripts\sync_android_secrets_from_fash.ps1 -FashRoot D:\Project\fash\fash-android-mobile -Push -Repo 333gih/personal-os
param(
    [string]$FashRoot = "D:\Project\fash\fash-android-mobile",
    [string]$Repo = "333gih/personal-os",
    [switch]$Push
)

$ErrorActionPreference = "Stop"
$PosRoot = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$FashEnv = Join-Path $FashRoot "secrets\android-release.env"
$FashKeystore = Join-Path $FashRoot "secrets\upload.keystore"
$FashPlayJson = Join-Path $FashRoot "secrets\play-service-account.json"

if (-not (Test-Path $FashEnv)) {
    Write-Error "Missing $FashEnv - open fash-android-mobile and fill secrets/android-release.env"
}

function Read-DotEnv([string]$Path) {
    $map = @{}
    Get-Content $Path | ForEach-Object {
        $line = $_.Trim()
        if ($line -eq "" -or $line.StartsWith("#")) { return }
        $eq = $line.IndexOf("=")
        if ($eq -lt 1) { return }
        $map[$line.Substring(0, $eq).Trim()] = $line.Substring($eq + 1).Trim()
    }
    return $map
}

$secretsDir = Join-Path $PosRoot "secrets"
New-Item -ItemType Directory -Force -Path $secretsDir | Out-Null

if (Test-Path $FashKeystore) {
    Copy-Item $FashKeystore (Join-Path $secretsDir "personal-os-upload.keystore") -Force
    Write-Host "Copied upload keystore -> secrets/personal-os-upload.keystore"
} else {
    Write-Warning "Fash keystore not found at $FashKeystore"
}

if (Test-Path $FashPlayJson) {
    Copy-Item $FashPlayJson (Join-Path $secretsDir "play-service-account.json") -Force
    Write-Host "Copied Play service account JSON"
}

$fashMap = Read-DotEnv $FashEnv
$out = @(
    "# Generated by sync_android_secrets_from_fash.ps1 - do not commit",
    "ANDROID_DEV_ENV_PATH=android/env/dev.env",
    "ANDROID_PROD_ENV_PATH=android/env/prod.env",
    "ANDROID_UPLOAD_KEYSTORE_PATH=secrets/personal-os-upload.keystore",
    "ANDROID_UPLOAD_KEYSTORE_PASSWORD=$($fashMap['ANDROID_UPLOAD_KEYSTORE_PASSWORD'])",
    "ANDROID_UPLOAD_KEY_ALIAS=$($fashMap['ANDROID_UPLOAD_KEY_ALIAS'])",
    "ANDROID_UPLOAD_KEY_PASSWORD=$($fashMap['ANDROID_UPLOAD_KEY_PASSWORD'])",
    "GOOGLE_PLAY_SERVICE_ACCOUNT_JSON_PATH=secrets/play-service-account.json",
    "PLAY_TRACK=POS-closed",
    "PLAY_EXPECTED_UPLOAD_SHA1=$($fashMap['PLAY_EXPECTED_UPLOAD_SHA1'])"
)
$destEnv = Join-Path $secretsDir "android-release.env"
$out | Set-Content -Encoding UTF8 $destEnv
Write-Host "Wrote $destEnv"

if ($Push) {
    & (Join-Path $PosRoot "scripts\push_github_android_secrets.ps1") -Repo $Repo -EnvFile "secrets/android-release.env"
}
